spring:
  application:
    name: user-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000


  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      jdbc:
        time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    username: "service"
    password: "service"
    url: "jdbc:postgresql://localhost:5432/ewm-userservice"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

server:
  port: 0


