spring:
  main:
    banner-mode: OFF
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      jdbc:
        time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    username: "service"
    password: "service"
    url: "jdbc:postgresql://localhost:5432/ewm-requestservice"

grpc:
  client:
    collector: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///collector' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext