spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true

      routes:
        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/hit/**
            - Path=/stats/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/users/**
            - Path=/admin/comments/**

        - id: main-service
          uri: lb://event-service
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
